# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "eb2ac16e73b1aa6a29c92a7c8549e3bf"
name = "sssync"
application_url = "https://backup-njx--development.gadget.app/api/shopify/install-or-render"
embedded = false

[build]
# Gadget manages all your scopes, webhooks and api versioning for your app
# As such, this line should not be changed unless you are working with
# Shopify managed installations. Read more at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml
include_config_on_deploy = false

[auth]
redirect_urls = ["https://backup-njx--development.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2024-10"
