import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://backup-njx.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    authToken: { type: "string", storageKey: "y00BfchrGyag" },
    users: {
      type: "hasManyThrough",
      sibling: { model: "user", relatedField: "shops" },
      join: {
        model: "shopPermission",
        belongsToSelfField: "shop",
        belongsToSiblingField: "user",
      },
      storageKey: "KafJtMw2ULgl",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "appCredits",
      "appInstallations",
      "appPurchaseOneTimes",
      "appSubscriptions",
      "appUsageRecords",
      "bulkOperations",
      "checkoutApiSupported",
      "city",
      "cookieConsentLevel",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "customerAccountsV2",
      "customerEmail",
      "domain",
      "domains",
      "eligibleForCardReaderGiveaway",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "files",
      "finances",
      "forceSsl",
      "fulfillmentEvents",
      "fulfillmentLineItems",
      "fulfillments",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "inventoryItems",
      "inventoryLevels",
      "latitude",
      "locations",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderAdjustments",
      "orderLineItems",
      "orders",
      "passwordEnabled",
      "phone",
      "planDisplayName",
      "planName",
      "preLaunchEnabled",
      "primaryLocale",
      "primaryLocation",
      "productMedia",
      "productOptions",
      "productVariantMedia",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "refundDuties",
      "refundLineItems",
      "refunds",
      "requiresExtraPaymentsAgreement",
      "setupRequired",
      "shopOwner",
      "shopifyBusinessEntity",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "transactionalSmsDisabled",
      "weightUnit",
      "zipCode",
    ],
  },
};
